// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAOv-LVUcXXGcSFuNaFdHErTZHfwShRqo',
    appId: '1:1054890031709:web:b46690b19925141a36ebb4',
    messagingSenderId: '1054890031709',
    projectId: 'mcq-application-14a70',
    authDomain: 'mcq-application-14a70.firebaseapp.com',
    storageBucket: 'mcq-application-14a70.appspot.com',
    measurementId: 'G-6R1TPZE3L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtolAV1rKPMEkHyhsEF8nUqLWucNPL4EI',
    appId: '1:1054890031709:android:7a3e6a259a0fd11d36ebb4',
    messagingSenderId: '1054890031709',
    projectId: 'mcq-application-14a70',
    storageBucket: 'mcq-application-14a70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqILYmy99oSClKSQDFqHFYj_HF73vmXEQ',
    appId: '1:1054890031709:ios:9dce8b5ba77c980036ebb4',
    messagingSenderId: '1054890031709',
    projectId: 'mcq-application-14a70',
    storageBucket: 'mcq-application-14a70.appspot.com',
    iosBundleId: 'com.example.flutterMcq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqILYmy99oSClKSQDFqHFYj_HF73vmXEQ',
    appId: '1:1054890031709:ios:9dce8b5ba77c980036ebb4',
    messagingSenderId: '1054890031709',
    projectId: 'mcq-application-14a70',
    storageBucket: 'mcq-application-14a70.appspot.com',
    iosBundleId: 'com.example.flutterMcq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAOv-LVUcXXGcSFuNaFdHErTZHfwShRqo',
    appId: '1:1054890031709:web:4df5ee3709dbfce936ebb4',
    messagingSenderId: '1054890031709',
    projectId: 'mcq-application-14a70',
    authDomain: 'mcq-application-14a70.firebaseapp.com',
    storageBucket: 'mcq-application-14a70.appspot.com',
    measurementId: 'G-YK2ME0V1B1',
  );

}